### ISSUE TITLE
G1 Coefficient Lookup Table Error

### ISSUE THREAD

**Issue by cecil1527** [Xerxes-17/TarkovGunsmith#94]
There's a bug/error in the [calculation of the G1 coefficient.](https://github.com/Xerxes-17/TarkovGunsmith/blob/fb499520d2de92b4805453f5384684e2dd909d52/BackEnd/WishGranter/Statics/Ballistics/RangeSimulation.cs#L303)

You're indexing into the table using multiples of 0.05 Mach, but that only works if each row is separated by 0.05 Mach, which isn't the case.

It can be fixed by making a more generic LUT that doesn't depend on the step size between rows.
* Store an array of inputs and an array of outputs.
    * Inputs would be the G1 table's Mach numbers
    * Outputs would be the G1 table's drag coefficients.
* Binary search through the inputs to find the floored index.
    * This gets you the index of the largest input from the table that's still smaller than the search value.
    * The search value would be the bullet's current Mach number in this case.
* Get ceilinged index. 
    * If you make your first binary search go from 0 to maxIndex - 1, then you can simply add 1 to the floored index to get a ceilinged index and it will always safely stay in bounds.
* Then you'll have your lower and upper indices and can lerp using the input and output at these indices.

**Comment by Xerxes-17** [comment]
I'd have to double check, but I believe that's from the original BSG implementation. 😅

**Comment by Xerxes-17** [comment]
@cecil1527 , I just checked and it is in fact how BSG has done it originally.
